# Generated by Django 5.0 on 2023-12-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg_encrypt', '0003_encryption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='encryption',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
