# Generated by Django 5.0 on 2023-12-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_encrypt', '0004_delete_encryption_delete_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('encryption', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('one_time_use', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Msgs',
        ),
    ]
